### ISSUE TITLE
Missing dot in documentation

### ISSUE THREAD

**Issue by cadar** [lfe/lfe#112]
In this page: https://registry.hub.docker.com/u/lfex/lfe/ 
There is a commando without a dot in the end. It should be:

docker build -t my-lfe-app .

**Comment by cadar** [comment]
For a smooth ride,
we don't want to refer to an docker image called "lfe:0.10" 
on this page: https://registry.hub.docker.com/u/lfex/lfe/ 
"lfe:0.10" does not exist for new users. 
It's better to only refer to "my-lfe-app". 
Since this one will exist if the user just built an image.

**Comment by oubiwann** [comment]
A _very_ belated response here ... I fixed the version issue last week and just fixed the "commando" (lI like your term) now.

A note on the version -- at the time the Dockerfile was created, the dev version had got bumped in the repo, but then went back to 0.9.x. It has since gone back up to 0.10.x, but hasn't been released yet. It was a moving target :-)

Feel free to close this issue, if it all checks out at your end (I don't have perms to close).
