### ISSUE TITLE
Atoms behaving strangely in lists

### ISSUE THREAD

**Issue by useronym** [lfe/lfe#119]
I'm having some trouble with atoms in lists:

```
> (set t1 '('ok 'ok))
('ok 'ok)
> (set t2 (lc ((<- _ (lists:seq 1 2))) 'ok))
(ok ok)
> (== t1 t2)
false
```

For some reason, declaring an atom in a list creates a list of [quote, atom]:

```
> '('ok)
('ok)
```

Compare this with just making a good old atom:

```
> 'ok
ok
```

The second one loses the quote, but the first one keeps it. Is this a bug, or am I missing something?

Defining the atoms inside the list without quotes produces a list of atoms

```
> '(ok ok ok)
(ok ok ok)
```

Is this expected behavior?

**Comment by oubiwann** [comment]
On Mon, Jun 1, 2015 at 9:03 AM, Adam K. <notifications@github.com> wrote:

> I'm having some trouble with atoms in lists:
>
> > (set t1 '('ok 'ok))
> ('ok 'ok)
> > (set t2 (lc ((<- _ (lists:seq 1 2))) 'ok))
> (ok ok)
> > (== t1 t2)
> false
>
> For some reason, declaring an atom in a list creates a list of [quote,
> atom]:
>
> > '('ok)
> ('ok)
>
>
Yes, this is expected behaviour (see below).

> Compare this with just making a good old atom:
>
> > 'ok
> ok
>
> The second one loses the quote, but the first one keeps it. Is this a bug,
> or am I missing something?
>

When you get results in the REPL, it's unquoted. When you enter code in the
REPL, you need to quote anything that would be ambiguous to LFE. If you
just entered the following in the REPL:

> ok

LFE would think you were referring to a variable named ok. When you quote
it, LFE knows it's an atom you are referring to:

> 'ok
ok

When you enter code in the REPL, you have two options: enter it as "data"
(e.g., quoted), or enter it as "code" (e.g., using constructor functions.
To enter a list of items using the second method, with a list constructor,
you just do this:

> (list 'a 'b 1 2 3 (tuple 'key 'value))
(a b 1 2 3 #(key value))

If you instead wanted to enter it as data, you'd do this:

> '(a b 1 2 3 #(key value))
(a b 1 2 3 #(key value))

Note that when you quote a form, everything enclosed in that form is
quoted. Above, we quoted that list, so we don't need to quote the atoms a
or b or the tuple.

If you want to use the "data" approach as above, but wish to have something
evaluated in the data, then you need to use backquote instead of regular
quote. Backquote allows you to then unquote things -- which is what you'd
want to do if you needed something evaluated in your data. For instance:

> (set some-data #(key value))
#(key value)
> '(a b 1 2 3 some-data)
(a b 1 2 3 some-data)

That uses single-quote and some-data is just interpreted as an atom. Heres
how you'd evaluate some-data in your list:

> `(a b 1 2 3 ,some-data))
(a b 1 2 3 #(key value))

Let me know if these notes don't answer your question ...

**Comment by oubiwann** [comment]
```
On Mon, Jun 1, 2015 at 9:03 AM, Adam K. <notifications@github.com> wrote:

> I'm having some trouble with atoms in lists:
>
> > (set t1 '('ok 'ok))
> ('ok 'ok)
> > (set t2 (lc ((<- _ (lists:seq 1 2))) 'ok))
> (ok ok)
> > (== t1 t2)
> false
>
> For some reason, declaring an atom in a list creates a list of [quote,
> atom]:
>
> > '('ok)
> ('ok)
>
>
```

Yes, this is expected behaviour (see below).

```
> Compare this with just making a good old atom:
>
> > 'ok
> ok
>
> The second one loses the quote, but the first one keeps it. Is this a bug,
> or am I missing something?
>
```

When you get results in the REPL, it's unquoted. When you enter code in the
REPL, you need to quote anything that would be ambiguous to LFE. If you
just entered the following in the REPL:

``` lisp
> ok
```

LFE would think you were referring to a variable named ok. When you quote
it, LFE knows it's an atom you are referring to:

``` lisp
> 'ok
ok
```

When you enter code in the REPL, you have two options: enter it as "data"
(e.g., quoted), or enter it as "code" (e.g., using constructor functions).
To enter a list of items using the second method, with a list constructor,
you just do this:

``` lisp
> (list 'a 'b 1 2 3 (tuple 'key 'value))
(a b 1 2 3 #(key value))
```

If you instead wanted to enter it as data, you'd do this:

``` lisp
> '(a b 1 2 3 #(key value))
(a b 1 2 3 #(key value))
```

Note that when you quote a form, everything enclosed in that form is
quoted. Above, we quoted that list, so we don't need to quote the atoms a
or b or the tuple.

If you want to use the "data" approach as above, but wish to have something
evaluated in the data, then you need to use backquote instead of regular
quote. Backquote allows you to then unquote things -- which is what you'd
want to do if you needed something evaluated in your data. For instance:

``` lisp
> (set some-data #(key value))
#(key value)
> '(a b 1 2 3 some-data)
(a b 1 2 3 some-data)
```

That uses single-quote and some-data is just interpreted as an atom. Heres
how you'd evaluate some-data in your list:

``` lisp
> `(a b 1 2 3 ,some-data))
(a b 1 2 3 #(key value))
```

Let me know if these notes don't answer your question ...

**Comment by useronym** [comment]
Ah, this makes it very clear to me. Thank you especially for explaining the difference in the backquote---macros make a lot more sense now :)

**Comment by oubiwann** [comment]
Sweet!

We hope you're enjoying LFE ... :-D

**Comment by useronym** [comment]
Well, it's Erlang, and it's a Lisp so... yeah, I am ;)
