### ISSUE TITLE
lfec doesn't set the exit code correctly under unix when compilation fails.

### ISSUE THREAD

**Issue by hdurer** [lfe/lfe#131]
I run this in a shell:

```
echo "invalid code" > foo.lfe
lfec foo.lfe && echo "This is wrong" || echo "Yay, it works"
```

The output is 

```
./foo.lfe:1: bad module definition: name
./foo.lfe:1: unknown form
This is wrong
```

I.e. lfec claim it succeeded.

**Comment by oubiwann** [comment]
Ordinarily, I would put the offending code into a function, do a try/catch and then halt with the appropriate code, e.g.:

``` cl
(try
  (compile)
  (catch (_ (halt 127))))
```

In this case, that doesn't work. If Robert doesn't get to it sooner, I'll take a look at `lfe_comp` and see how it's handling a bad file (it's not a simple exception, or the above would work).

**Comment by oubiwann** [comment]
Alright, I had a chance to take a look at this. `lfe_comp` doesn't throw an error because it needs to track all possible failures (if 100 files are compiled, it wants the user to see a report with all of them, and not have to run 100 compiles after fixing each file individually).

As such, `lfe_comp:file` returns a tuple of `{error, Errors, Warnings}`.

I've got a patch ready that does `(halt 1)` in `lfec` when there is `{error, Errors, _}` but not `{error, [], Warnings}`. I'll submit it for Robert's review later today.

Thanks for the catch!

**Comment by rvirding** [comment]
Lfe_comp should never return `{error,_,_}` unless there are errors. If there are only warnings and no errorrs then it returns `{ok,_,_}`. The actual errors and warnings are only returned if `return` is an options and only printed if `report` is an option.

**Comment by oubiwann** [comment]
Ah, good to know -- I'll turn off `return` then and just check for `error`. That'll be much cleaner :-)

**Comment by rvirding** [comment]
This has been fixed.
