### ISSUE TITLE
Limit character literals roughly to the Unicode range?

### ISSUE THREAD

**Issue by hdurer** [lfe/lfe#147]
`#\x1000000000000000000000` will never be a valid character, so maybe we should do a sanity check on the value.

**Comment by rvirding** [comment]
Actually this handling of `#\x` is pretty stupid as it means I can't directly write the character x like this, I have to know its unicode value. I don't know where I got it from as neither scheme nor CL has it. Maybe from erlang where you can do `$\xff` and `$\n`. Something has to be done to clean this up.

**Comment by rvirding** [comment]
A correction here about `#\x`. If you just write `#\x` then you **do** get the value of the character `x,` 120, but if you write `#\xdfff` then you get the character value `#xDFFF`. A bit confusing maybe. The only benefit of using `#\xDFFF` instead of `#xDFFF` would be that as **know** it is a character then we can add the suggested value check.

**Comment by hdurer** [comment]
Agreed.  To me #\x.... is the same as #x... except
a) it signals to the reader that a character and not just any number is
meant and
b) lfe does a sanity check on the value (it won't allow negative values or
values clearly out of the Unicode range)
