### ISSUE TITLE
rebar3 failing to compile LFE

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#161]
When trying to compile LFE with rebar3, this error is reported:

``` bash
$ DEBUG=1 rebar3 compile
```

``` erlang
===> Compiling lfe
===>      Skipped lfe_scan.xrl
===>      Compiled lfe_lib.erl
===>      Compiled lfe_env.erl
===>      Compiled lfe_comp.erl
===>      Compiled lfe_io.erl
===> Compiling /home/oubiwann/lab/lfe/lfe/_build/default/lib/lfe/src/lfe_scan.erl failed
/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:47: attribute 'dialyzer' after function definitions
/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:118: attribute 'dialyzer' after function definitions
/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:194: attribute 'dialyzer' after function definitions
/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:247: attribute 'dialyzer' after function definitions

===> Compilation failed: {error,
                                    [["/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:47: attribute 'dialyzer' after function definitions\n",
                                      "/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:118: attribute 'dialyzer' after function definitions\n",
                                      "/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:194: attribute 'dialyzer' after function definitions\n",
                                      "/opt/erlang/18.0/lib/parsetools-2.1/include/leexinc.hrl:247: attribute 'dialyzer' after function definitions\n"]],
                                    []}

```

**Comment by rvirding** [comment]
Is it running dialyzer, either explicitly or implicity? Dialyzer normally complains about leex generated code because the boilerplate code can handle more return alternatives than are used in most cases. In leexinc.hrl at the lines 47, 118, 194 and 247 there is a dialyzer control attribute to stop the warnings which seems to be causing problems as it is not last:

-dialyzer({nowarn_function, skip_cont/4}).

Strangely enough I don't get any errors or warnings from this when I compile erl_scan even though the attribute is in the file. What compiler options are used? I compile with both erlc and rebar2.

Robert

**Comment by oubiwann** [comment]
Hrm, we might need @ferd or @tsloughter for this one; I don't know the answers to your questions, but I'll dig around and see.

**Comment by oubiwann** [comment]
False alarm! This is an invalid bug :-/

I hadn't done `make clean` before building with a different version of Erlang.

Sorry about that!
