### ISSUE TITLE
Consider writing rebar3 templates and shipping them with LFE

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#203]
If you put rebar3 templates in `priv/` at the project root, they're usable in projects that depend on them.

I think it'd be cool to be able to do:

``` sh
$ rebar3 new lfe sup
$ rebar3 new lfe gen_server
$ rebar3 new lfe unit-test
```

etc

**Comment by oubiwann** [comment]
Here are my thoughts:
- basic library template -- cool
- OTP templates (for `gen_server`, `get_event`, `gen_fsm`, etc.) -- cool
- templates that require any other library in order to be useful -- I'd vote for those going in their respective library's `priv` dirs ...

Regardless, this capability of rebar3 is neat; I didn't know that it would take advantage of the deps libs `priv` dirs for templates.

**Comment by yurrriq** [comment]
Agreed. For templates packaged with the language, I was thinking just barebones stuff like OTP behaviours and maybe super generic application and library templates.

**Comment by rvirding** [comment]
Now I have to expose my ignorance here. Why would I need a template for
gen_server etc? And what is in such a template?

Robert
