### ISSUE TITLE
Empty list in function definition

### ISSUE THREAD

**Issue by fooflare** [lfe/lfe#245]
Hi,
I am not sure if this is an issue or if I have a misunderstanding. I try to write the below Erlang function in lfe:

```
init([]) ->
    {ok, { {one_for_all, 0, 1}, []} }.
```

It seems simple but... If I compile:

```
(defun init ('()) 
  (tuple 'ok (tuple (tuple 'one_for_all 0 1) '())))
```

I get:

```
./my-sup.lfe:20: head arity mismatch
./my-sup.lfe:20: illegal pattern
./my-sup.lfe:9999: unbound function: #(init 1)
```

When I rewrite this to:

```
(defun init (('()) 
  (tuple 'ok (tuple (tuple 'one_for_all 0 1) '()))))
```

it compiles successfully, but I think it is not the right way because there is no more patterns.

Thanks.

**Comment by rvirding** [comment]
It is the right way.

You have 2 basic forms for `defun`: either `(defun func (<arg names>) <body>)` or `(defun func <clauses>)`. If you want pattern matching then you must use the clause form even if there is only one clause. `defun` checks by looking at first form after the func name and if it is a list of symbols then it assumes it is the 1st form otherwise it assumes it is the 2nd. Which is what it was doing with you code and when the patterns didn't match it complained about the arity.

So you would have to write your function as

```
(defun init
  ([()] (tuple 'ok (tuple 'one_for_all 0 1))))
```

The `[]` is equivalent to `()` and is a list and I find it useful to make things easier to read as in this case where I use it for the list of arguments. There is no need to quote `()`, it is not wrong but not needed.

**Comment by yurrriq** [comment]
The latter is indeed correct. That version of init/1 has one function clause with a pattern that matches a single parameter that is the empty list.

I like to write mine like this, since square brackets and parentheses are interchangeable:

``` lfe
(defun init
  ([()]
   #(ok #(#(one_for_all 0 1) []))))
```

A couple more notes:
- There's no need to quote the empty list.
- Since all the values in the (nested) tuple are literal, we can use the literal tuple syntax, `#(...)`, and not worry about quoting.

**Comment by fooflare** [comment]
Thank you so much for your explanations. Now I have it clear.

**Comment by yurrriq** [comment]
Oops, I missed Robert's response. It might also be helpful to inspect the output of `(macroexpand '(defun {{function clause}}))`.
