### ISSUE TITLE
Syntax Questions

### ISSUE THREAD

**Issue by trans** [lfe/lfe#254]
Hi, I've been hunting for a new language to learn. I have always liked lisp so modern variations are high on my list. On the other hand I am very adverse to esoteric and extraneous syntax. So looking at the example code on the website I have a few questions.
1.  In `(io:fwrite '"Result: ~b~n" (list id))`, why is the single-quote needed before the double-quote?
2. In the same snippet, why is `list` needed?
3. The prefix to denote a function, e.g. `#'make-process/2`, seem especially ugly to me since `#` is a comment marker in many other languages. I wonder, since this is _Erlang_ based if the language can't just be made to recognize the `/` and know then that it is a function name.
4. In `(spawn 'ring 'roundtrip (list id pid)))`, that seems inconsistent. Why isn't it `(spawn 'ring #'roundtrip/2 ...`, and beyond that it seems odd that spawn takes a module name as a separate argument. I would think there would need to be a way to specify a function including the module in a single notation, e.g. `(spawn #'ring:roundtrip/2 ...`.
5. Where did the double-quote multi-line comment notation come from? Personally I prefer the `;;` on each line, but even so, at least the multi-line form's markers should not be so easily confused with a string atom. Also, can it start on the prior line, e.g. using `--` instead of `"`.
   
   ```
   (defun main (args) --
       Call with the following:
           $ lfec ring.lfe
           $ lfe -smp disable -noshell -run ring main 503 50000000
       --
   ```
   
   Of course, I never much cared for putting the comment inside the function definition anyway because is separates the arguments from the rest of the code. But I suppose that doesn't really matter b/c unless there are enforced documentation rules it is still an option (to put them above the defun)?

**Comment by oubiwann** [comment]
@trans Glad you're checking out LFE!

1) That's a doc bug, since strings are no longer required to be Lisp-quoted (I forget when that landed ... maybe somewhere around LFE 0.7?)

2) `(list ...)` is needed because the Erlang function `frwite` in the stdlib module `io` takes a list as an argument. That being said, you can use the list "constructor" (function form) or you can use a list literal (data form). As such, the following are equivalent: 

``` cl
(io:fwrite "Result: ~b~n" (list id))
```

and

``` cl
(io:fwrite "Result: ~b~n" `(,id))
```

I tend to use the latter when I've just got data. 

But, to answer the _spirit_ of your question (perhaps paraphrased as "When I'm passing a single argument, do I have to put it in a list? Can't the language check to see if it's a single value or if it's multi-valued and do the "right thing"?), Erlang (and thus LFE) is fixed-arity language -- a function that takes one argument and a function that takes 2 arguments are actually _different functions_, even if the logic is identical.

As such, we could write our own `fwrite` that does something like this:

``` cl
(defun fwrite (tmpl arg)
    (io:fwrite tmpl `(,arg)))

(defun fwrite (tmpl arg-1 arg-2)
    (io:fwrite tmpl `(,arg-1 ,arg-2)))
```

Obviously this would get tedious for supporting arbitrary args :-) You can use LFE macros to get around the limitation of fixed arity in Erlang, but then you've got macros and not functions, and you'll be limited as to what you can do with composition, etc. 

3) That's actually been borrowed from Common Lisp and Scheme (and before that, MACLISP). In fact, Clojure also uses this syntax. It may seem odd, but once you use more Lisps or spend more time with them, the eye adapts.

A further note on syntax: LFE tries to be as Lisp-y as possible ... borrowing Erlang syntax and putting that in LFE is actually a bad smell for LFE :-)

4) Ah, yes -- here you've touched upon one of the common experiences of Erlang users: the inconsistencies present in the standard library. Erlang libs were built over time (20+ years) and by different people, so the experience isn't as unified as it would be if a single person (or small, tightly-knit team) built them in a short time. In this particular case, it's not a function that gets passed to the Erlang `spawn` function, but rather a module name (atom) and a function name (atom) in that module. See the Erlang docs [here](http://erlang.org/doc/man/erlang.html#spawn_link-3) for more info on `spawn/3` usage. Some Erlang stdlib functions will take a module/function atom pair, some will take an actual function. There are good reasons for these (sometimes a bit shrouded in the mists of history), and the reasons differ ... another reason for such inconsistencies. In the case of `spawn` it really does make sense when you consider the rpc-like nature of spawning mod:func on remote nodes ...

5) If you mean the quoting for docstrings, this has been in Lisp for a long time (also Scheme and Clojure). Actual line comments use the semi-colon (`;` for end-of-line, `;;` for beginning of line inside a function, `;;;` at beginning of lines for separating parts of code in a module, or module-level comments, and `;;;;` at beginning of lines at the very top of the module -- this practice is inherited from Common Lisp). LFE also supports Common Lisp style multi-line comments (different from docstrings) which use the `#| ... |#` syntax.

The function and macro docstrings are part of LFE syntax -- they can only go in one place. If you do something else, LFE won't know what you're doing or what your intent is. Furthermore, documentation tools (i.e., lodox) won't be able to generate doc pages from your code.

That being said, you have complete freedom to do whatever you want -- there are just risks that need to be assessed for the sake of your future sanity and happiness :-)

**Comment by yurrriq** [comment]
Thanks for answering this, @oubiwann. Fair warning re: [lodox](https://github.com/LFE-rebar3/lodox) (author here), it's not been updated for recent versions of LFE and much of it has been reimplemented more deliberately in LFE proper. I need to write an update for LFE >= 1.02 or so.

**Comment by trans** [comment]
Thanks for the answers. That was very helpful.

With regard to 2. Why can't one write: `(io:fwrite "Result: ~b~n" ((id)))`? Wouldn't the inner `(id)` be a list? Also, could you explain ``(,id)` notation? I am a little confused, how does `'` differ from backtick?

For 3, good that LFE is following standards and traditions, though I don't think it necessarily should prevent innovation either. Certainly code would read better if one could just write `make-process/2` as an alternative to `#'make-process/2`.

Finally 5, thanks for giving me the name "docstrings" I was able to look it up and get an understanding. Seems like someone decided to take advantage of a "syntax hole", so to speak, that a string at the start of a function definition is useless, and so decided to make a use for it. I'm still dubious of the placement but at least I understand it now. So are these docstrings really useful in one's code? -- I don't mean for generating documentation, that can be done other ways too. I mean, does it help with debugging, errors, usages via the `documentation` call, etc?

**Comment by yurrriq** [comment]
Dissecting `((id))`: The inner form `(id)` would try to call a nullary function `id`. And since LFE is a Lisp-2(+), `((id))` would try to call a nullary function `(id)` which isn't possible to define (need to confirm) since parentheses are reserved characters. You could, however, name a function `(id)` if you surrounded it with pipes:

``` lfe
> (defun |(id)| (x) x)
|(id)|
> (|(id)| 42)
42
```

---

`'` quotes a form. iirc it expands to `(quote ...)` internally. Quoted forms are not evaluated (think literal `x` vs the value of evaluating `x`).

``` is the same thing, except it lets you _unquote_ with `,`. So everything that's not _unquoted_ similarly won't be evaluated, but the unquoting lets you sneak in some evaluation.

In the case of `(,id)` you're quote the structure of a singleton list and unquoting (and thus evaluating) `id`, i.e.

``` lfe
`(,id) == (list id)
```

`'(id)` otoh would also be a singleton list, but it wouldn't evaluate `id`. Instead it's the singleton list containing the atom `id`.

---

The docstrings can be stripped from the resulting BEAM module by passing the `+no-docs` flag to the compiler. They're really only useful to humans and can be quite handy in a REPL via `(doc ...)`.

**Comment by trans** [comment]
With the exception of "try to call a nullary function `(id)`", everything is clear to me now. But suffice to say the Lisp-2 info is enough to make me realize it will try to call `id` as a function and not as a reference to the variable.

Thanks. I appreciate you taking the time to answer.

**Comment by yurrriq** [comment]
I'm glad we were able to help! If you haven't already, you might be interested to join the discussions on IRC (#erlang-lisp on freenode) or the Slack (I don't have the link handy, but I think it's lfe.slack.com).

**Comment by yurrriq** [comment]
@trans lodox 0.15.1 should work with lfe 1.1.1

https://github.com/lfe-rebar3/lodox/releases/tag/0.15.1
