### ISSUE TITLE
Update Makefile

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#301]
Pulled out from the thread on #244.

- [x] ~~Decouple `install-man` from `install` (thus obviating the *need* for `pandoc`)~~
- [x] Fold in some of the [Elixir `Makefile`](https://github.com/elixir-lang/elixir/blob/v1.3.4/Makefile#L99)-inspired changes from the [LFE Nix package](https://github.com/NixOS/nixpkgs/blob/16.09/pkgs/development/interpreters/lfe/default.nix#L19)

**Comment by oubiwann** [comment]
@yurrriq [This PR](https://github.com/rvirding/lfe/pull/298/files) decouples the man build from man install -- we still want man pages installed ... but they're pregenerated and tracked in source, so installing them is no problem. The problem was that before that PR, `install-man` also built them ...
