### ISSUE TITLE
Expanding Erlang macro into module name is not supported

### ISSUE THREAD

**Issue by KrzysiekJ** [lfe/lfe#334]
Let’s say we have the following `.hrl` file:

```erlang
-define(LISTS_MODULE, lists).
-define(BAR, ?LISTS_MODULE:seq(1,10)).
```

Then writing `(BAR)` gives the following error:

```
function #(BAR 0) undefined
```

Replacing `?BAR` definition with the following gives no error:

```erlang
-define(BAR, lists:seq(1,10)).
```

**Comment by yurrriq** [comment]
Looks like a bug to me. Thanks!

**Comment by rvirding** [comment]
No, this is not really bug but the effect of how macros work in Erlang and in LFE.

Macros in Erlang are based on tokens before parsing while LFE macros, like most lisps, are based on parsed s-expressions. [*] The `?`  in Erlang indicating a macro is to be expanded is thus never seen by the parser and is illegal syntax there. So when translating Erlang macros we have to parse them into a legal Erlang AST and then convert that to LFE. So when a `?` is encountered we have to convert that into something able to be parsed and which can later be detected by LFE as call to a macro and then expanded. So we convert them syntactically to function calls. So for an example from `eunit.hrl`:

```
-define(_assert(BoolExpr), ?_test(?assert(BoolExpr))).
```

the body will be converted to the Erlang `_test(assert(BoolExpr))` which will later be converted to the LFE ``(defmacro _assert (BoolExpr) `(_test (assert ,BoolExpr)))`` which does what we want. `_test` and `assert` are macros.

So in your example the body of `BAR` will be converted to the Erlang `(LISTS_MODULE):seq(1,10)` which is not parseable Erlang. The problem is then what could we convert your example into so it is correct Erlang which could then be converted into something sensible in LFE. And which is reasonable to detect.

[*] This means that it is legal to define Erlang macros which don't expand into valid Erlang syntax but must be used together with other macros. This we cannot handle in LFE. For example the macros

```
-define(BEGIN, begin).
-define(END, end).
```

which must be used as a pair.

**Comment by yurrriq** [comment]
Perhaps we could come up with a list of reasonable cases (such as the example above) to handle specially. The `?BEGIN`/`?END` example is unreasonable by my estimation. Perhaps the list of reasonable special cases could start with just `?MACRO_EXPANDING_TO_MOD:fun(...)`.

I suppose this only really matters if there's a third-party library that has such macros in a `.hrl` that an LFE user needs. Do you have such an example, @KrzysiekJ?

**Comment by rvirding** [comment]
A library with useful macros is eunit, but it is not 3rd party of course.

**Comment by yurrriq** [comment]
That seems to work fine though.

```lfe
lfe> (lfe_io:prettyprint (macroexpand-all '(_assert (=:= 4 (+ 2 2))) $ENV))
(tuple
 '1
 (match-lambda
   (()
    (when)
    (progn
      (funcall (match-lambda
                 (()
                  (when)
                  (let ((__T (when) (is_process_alive (self))))
                    (case (call 'erlang '=:= 4 (call 'erlang '+ 2 2))
                      (---0--- (when (call 'erlang '=:= __T ---0---)) 'ok)
                      (__V
                       (when)
                       (call 'erlang
                             'error
                         (tuple
                          'assert
                          (list
                           (tuple 'module '-no-module)
                           (tuple 'line '1)
                           (tuple
                            'expression
                            (call 'lfe_macro_include
                                  'stringify
                              '(=:= 4 (+ 2 2))))
                           (tuple 'expected 'true)
                           (case (not __T)
                             (---1---
                              (when (call 'erlang '=:= __V ---1---))
                              (tuple 'value 'false))
                             (_ (when) (tuple 'not_boolean __V))))))))))))))))
```

What I was after was some `.hrl` that has tricky (and currently broken) macros (like the original example above), such that the macros or the library are particularly useful to LFE users.

**Comment by rvirding** [comment]
Ah. I have a fix for the specific case above which I will release next week. I don't have any suggestions for useful libraries with macros that are broken.

Unfortunately there is no API which allows me to explicitly expand erlang macros without losing the macro definitions. The interface I am using now is undocumented but pretty basic and doesn't really do anything weird from epp's POV.

**Comment by yurrriq** [comment]
Right. Me neither. This fix seems like a good enough start :smile:

**Comment by rvirding** [comment]
The latest push to develop contains a fix for this case. Please test.

**Comment by KrzysiekJ** [comment]
Thank you, it seems to work now. The problematic library has been [triq with its definition of `DOMAIN_MODULE` macro in the header file](https://github.com/triqng/triq/blob/3a47a996ab1feb5ba491046d5c972b7b1a9c7039/include/triq.hrl#L24), though it has been an issue quite easy to bypass anyway.
