### ISSUE TITLE
Fix Travis build

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#339]
The build is currently failing on Travis. I believe this is unrelated to #338.

**Comment by yurrriq** [comment]
Using `git bisect` it seems 69a2d1d410220a688ad169366d0d20e138e264f6 broke `ms_transform_SUITE`.

**Comment by yurrriq** [comment]
It looks like [`lfe_ms:is_ms_func/3`](https://github.com/rvirding/lfe/blob/69a2d1d410220a688ad169366d0d20e138e264f6/src/lfe_ms.erl#L240) fails for the [`records` tests](https://github.com/rvirding/lfe/blob/69a2d1d410220a688ad169366d0d20e138e264f6/test/ms_transform_SUITE.lfe#L123) and also [`lfe_ms:expr/2`](https://github.com/rvirding/lfe/blob/69a2d1d410220a688ad169366d0d20e138e264f6/src/lfe_ms.erl#L154) doesn't have a function clause for, e.g.

```erlang
expr([[rec,[object]]], #ms{dc=1,bs=[],where=guard}).
```

/cc @rvirding

**Comment by rvirding** [comment]
I think one problem is that the new testing of the record in the record macros is done using a `let` to ensure that the record argument is only evaluated once. This is not a problem in the body but lets are not allowed in the guard. This will mean some more study of how erlang does it.

**Comment by rvirding** [comment]
I now see that lets are allowed in guards but only in a restricted way. Still testing though. With a bit of luck we can have testing in the record macros.

**Comment by rvirding** [comment]
The problem is accessing record keys in the guard and body. I will look at fixing that.

However I saw that there was another Travis problem which also occurred before I made my fix. When testing with R16 and 17 versions there is a problem compiling proper. It worked when building v1.2.1 so I am guessing it is a recent version. Any suggestions welcome. Can rebar3 handle having different dependencies for for different OSs?
