### ISSUE TITLE
How to use typer and dialyzer on core erlang from LFE

### ISSUE THREAD

**Issue by lin7sh** [lfe/lfe#344]
I noticed the typer branch has been merged into the master,  I gave it a try

```
(define-module test
    () ((export all)))

(defspec (first 1)
    (((list (atom))) (atom)))

(define-function first
    () (lambda (lat)
        (car lat)))
```

and compile it with
`lfec +to-core +debug-info test.lfe`

then try it with dialyzer
`dialyzer test.core`
```
  Checking whether the PLT /Users/mko/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
dialyzer: Analysis failed with error:
Could not scan the following file(s):
  Could not get abstract code for: /Users/mko/Repo/lfe/test/test.core
  Recompile with +debug_info or analyze starting from source code
Last messages in the log cache:
  Reading files and computing callgraph...
```
and I have no luck with typer either
`typer schemer.core`

`typer: no file(s) to analyze`

Can anyone tell me how to do it correctly?

**Comment by rvirding** [comment]
I have done work on this now and with the latest commit to the 'develop' branch this now works. It does however require that dialyzer/typer is running on Erlang 20. While the generation works with LFE built/run on older versions of Erlang dialyzer needs to be the latest.

**Comment by lin7sh** [comment]
@rvirding thanks for the works on this useful feature, more I dig into LFE more I found the beauty in it

**Comment by lin7sh** [comment]
I update to the latest develop branch and make sure I'm running the erlang 20 as you mentioned. But still doesn't work
```
Argo@air.local:$ lfec +to-core +debug-info type-test.lfe 
Argo@air.local:$ dialyzer type-test.core 
  Checking whether the PLT /Users/Argo/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
dialyzer: Analysis failed with error:
Could not scan the following file(s):
  Could not get abstract code for: /Users/Argo/Repo/lfe/tmp/type-test.core
  Recompile with +debug_info or analyze starting from source code
Last messages in the log cache:
  Reading files and computing callgraph... 
Argo@air.local:$ typer type-test.core 
{"init terminating in do_boot",{undef,[{dialyzer_codeserver,get_temp_records,[{codeserver,0,#Ref<0.3496659132.3676700674.100289>,#Ref<0.3496659132.3676700674.100293>,#Ref<0.3496659132.3676700674.100292>,#Ref<0.3496659132.3676700674.100290>,#Ref<0.3496659132.3676700674.100291>,#Ref<0.3496659132.3676700674.100295>,#Ref<0.3496659132.3676700674.100294>,#Ref<0.3496659132.3676700674.100296>,#Ref<0.3496659132.3676700674.100297>,#Ref<0.3496659132.3676700674.100298>,#Ref<0.3496659132.3676700674.100299>}],[]},{typer,extract,2,[{file,"typer.erl"},{line,139}]},{typer,start,0,[{file,"typer.erl"},{line,89}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{dialyzer_codeserver,get_temp_records,[{_}],[]},{typer,extract,2,[{_},{_}]},{typer,start,0,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

```

**Comment by rvirding** [comment]
Sorry for not answering earlier.

The issue here is how dialyzer gets its information. While it internally uses the Core erlang for processing it can only read either .erl files or the compiled .beam files, nothing else. If it gets a .erl it compiles the file to generate the core erlang which it then uses. If it gets a .beam file then it uses a "chunk" in the file which has been generated with the `debug_info` option to get the information. The change which came in Erlang 20 affects this 2nd alternative.

In older pre Erlang 20 this chunk in the .beam contained the erlang AST which then dialyzer then compiled to the Core erlang, pretty much the same as compiling the .erl file. This was hard wired in dialyzer and you couldn't do much about it.[*]

In Erlang 20 this chunk now contains data in an unspecified format and the module of an access function to extract code from this data. So you call the function with one argument to get erlang AST and another to get Core erlang. Dialyzer now directly extracts the Core erlang from this data and does not go through the Erlang AST. So now the LFE compiler generates a chunk which from which you can get Core erlang which makes dialyzer happy.

So now you do:

    ~$ lfec +debug-info db.lfe
    ~$ dialyzer -pa lfe/lfe/ebin db.beam
      Checking whether the PLT /Users/rv/.dialyzer_plt is up-to-date... yes
      Proceeding with analysis...
    :1: The pattern {'yes', _exp} can never match the type 'no'
    Unknown functions:
      lfe_env:new/0
      lfe_eval:expr/1
     done in 0m0.14s
    done (warnings were emitted)

I am just specifically adding where dialyzer is to find the LFE libraries. In the next patch I will add flags to generate the debug info by default for the LFE libraries. But you must be using Erlang 20 for this to work.

I hope this helps.

[*] I previously did an experimental hack to dialyzer so it could recognise .lfe files and compile them, but then it wouldn't recognise .erl files. Sigh. The dialyzer interface leaves a lot to be desired.

**Comment by lin7sh** [comment]
@rvirding Thanks for the detailed explanation, it makes a lot sense, I think this information would also useful for other LFE users

**Comment by rvirding** [comment]
Probably, I just don't know where to put it. Something for the future.
