### ISSUE TITLE
Lack of documentation for lfec use / sample source file.

### ISSUE THREAD

**Issue by ahungry** [lfe/lfe#366]
I am trying to put together the simplest example of 'compiling' a hello world lfe file.

I can see how to run such a file via lfescript using the factorial example, but do not understand how to generate a (native?  erlang module?) file using lfec (it pauses and will print if the file I am using as a source file has errors, but it never seems to generate any output anywhere).

**Comment by oubiwann** [comment]
Yeah, the CLI help doesn't give much usage information. If you can read the arcana in a `Makefile`, that might be the best place to look. In another Github issue ( #368) I just showed how to compile a module (in a running Docker container, but that's beside the point):

```
$ mkdir examples/ebin
$ lfec -I include -o examples/ebin examples/ring.lfe
```
That compiles `ring.lfe` to `examples/ebin/ring.beam`, at which point it can be run with the following, since Erlang will know where to find `ring:main` when you tell it use add `examples/ebin` to the path:

```
$ lfe -pa examples/ebin -smp disable -noshell -run ring main 503 50000000
```

**Comment by oubiwann** [comment]
I've updated the CLI usage to include an example:
```
$ ./bin/lfec -h
```
```
Usage: lfec [options] file ...

Options:

-h             Print usage and exit
-I name        Name of include directory
-o name        Name of output directory
-pa path       Add path to the front of LFE's code path
-pz path       Add path to the end of LFE's code path
-v             Verbose compiler output
-Werror        Make all warnings into errors
-Wnumber       Set warning level (ignored)
-D             Equivalent to +debug-print
-L             Equivalent to +to-lint
-E             Equivalent to +to-exp
-S             Equivalent to +to-asm
--             No more options, only file names follow
+term          Term will be added to options

Terms include:

+binary, +no-docs, +to-exp, +to-lint, +to-core0, +to-core, +to-kernel, +to-asm
+{outdir, Dir}, +report, +return, +debug-print

Example:

$ lfec -I include -o ebin examples/ring.lfe
```

**Comment by ahungry** [comment]
Thanks for the update and issue resolution.
