### ISSUE TITLE
Minimum / Maximum supported OTP version for 1.3?

### ISSUE THREAD

**Issue by paulreimer** [lfe/lfe#385]
I'm curious about the current released `lfe` version (1.3), and what versions of OTP are supported.

I'm currently using `nix` to manage my packages, and I notice in the `lfe 1.2.1` recipe, that it does not permit Erlang/OTP versions greater than 19 (why was that?): 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/lfe/1.2.nix

I'm more concerned about what are the current OTP requirements for `lfe`, and whether a maximum version limit still applies in `lfe 1.3` and/or `lfe master`. (The `src/changelog` file seems to have stopped in 2013, and I haven't found much info about the original OTP restriction and why it may have been necessary at the time).

**Comment by oubiwann** [comment]
Hey, Paul!

I've recently done a bunch of testing against different versions of OTP and
the latest work being done on LFE.

Since LFE 1.4 isn't out yet, I pulled together various open pull requests
(many of which I think Robert has since merged!) and have tracked them here:
* https://github.com/lfe/lfe/tree/bleeding-edge

I'll be updating that soon to rebase off of Robert's latest merges. So
that's some of the newest stuff in LFE.

As for OTP, I have built Docker images using the bleeding-edge branch above
with all the latest OTP releases, and those are here:
* https://hub.docker.com/r/lfex/lfe/tags

I have not tested all of them thoroughly, so caveat emptor.

d

**Comment by yurrriq** [comment]
Re: Nix. I'm listed as a maintainer of the package, along with @ankhers, but haven't touched it in some time. It definitely needs updating. Which version(s) do you want to see in nixpkgs?

See also:
- https://github.com/NixOS/nixpkgs/pull/27295
- https://github.com/NixOS/nixpkgs/issues/11748

**Comment by paulreimer** [comment]
I’m just getting started with LFE; I’d be happy with 1.3 (the latest official release), if it works with the latest OTP (nixpkgs has R22) and doesn’t have any issues of its own.

**Comment by oubiwann** [comment]
Good news that LFE 1.3 works for you, @paulreimer!

I just filed a ticket that LFE doesn't pass all the tests on Erlang 22 (see https://github.com/rvirding/lfe/issues/386), just so you know. 

However, versions 18 though 21 have been smooth as silk for a while.

17 and 16 can be rocky sometimes ...

**Comment by paulreimer** [comment]
@oubiwann @yurrriq thanks for your help in this!

I just wanted clarify that I haven’t yet installed / used LFE (any version), just that I got stuck trying to install it with nix.

**Comment by oubiwann** [comment]
If you want to start playing with the REPL immediately, you could do this:
```
$ docker run -it lfex/lfe:1.3-21.3-alpine
```

**Comment by oubiwann** [comment]
I know nothing about nix, so can't help you there :-(

**Comment by yurrriq** [comment]
@paulreimer https://github.com/NixOS/nixpkgs/pull/78895

Looks like I had done most of the work in May 2018, but never submitted a PR :man_facepalming:

**Comment by oubiwann** [comment]
I'm going to close this as answered :-)
