### ISSUE TITLE
Compilation error when binary pattern matching with size variable

### ISSUE THREAD

**Issue by eternal-turtles** [lfe/lfe#437]
Hi. I am seeing a compilation error with a file that looks like the following:

```lisp
(defmodule example
  (export (size-variable-test 0)))

(defun size-variable-test ()
  (let* ((n 8)
         ((binary (initial-char bits (size n)) (rest-chars bits)) #"ABC")
         ('true (== #"A" initial-char))
         ('true (== #"BC" rest-chars)))
    initial-char))
```

```sh
$ rebar3 lfe compile
===> Verifying dependencies...
===> Compiling example
===> Compiling src/example.lfe failed
/home/jack/code/example/src/example.lfe:4: variable '-n-1-' is unbound
```

Loading the function directly in the REPL is OK and produces the desired result when called.
This seems possibly related to https://github.com/lfe/lfe/issues/430 which I am not able to reproduce.

Version info (with the offending function and its export statement commented out):
```sh
$ rebar3 lfe versions
===> Verifying dependencies...
===> Compiling example
(#(apps (#(example git)))
 #(languages
   (#(lfe "2.0.1")
    #(erlang "24")
    #(emulator "12.2.1")
    #(driver_version "3.3")))
 #(tooling (#(rebar "3.18.0") #(rebar3_lfe "0.4.0"))))
```
Also, to be clear, when the size is specified directly, it compiles without incident:

```sh
(defmodule example
  (export (size-variable-test 0)))

(defun size-variable-test ()
  (let* (((binary (initial-char bits (size 8)) (rest-chars bits)) #"ABC")
         ('true (== #"A" initial-char))
         ('true (== #"BC" rest-chars)))
    initial-char))
```

Thank you,
Jack

**Comment by rvirding** [comment]
Sorry for not replying earlier. Yes, this a bug in how the LFE compiler handles variables inside binary patterns. I must check this and get it working in the same way as the erlang compiler does it.

**Comment by rvirding** [comment]
Actually the problem is more complex than this and is not really a bug but an effect of how LFE handles variables in patterns. In Erlang there is no variable scoping and variables in patterns which have been bound before that get their values “imported” into the pattern. This is why the `N`  in the corresponding Erlang code would have its value imported and used for the size. However, LFE does have variable scoping and all variables in a pattern are new variables which shadow any values they may have been bound to before. This is why the `n` variable in the LFE code is reported as unbound by the Erlang compiler which is used by the LFE compiler to generate BEAM code.

So that is why it is not really a bug, it is just a difference in how variables are handled. I don’t really have a solution to this. It would be possible to special case some variables but I wouldn’t really want to do this. I will see if I can come up with a workable solution for this here.

EDIT: What I meant by the corresponding code is a direct rewrite of the LFE code in Erlang
```
-module(example).
-export([size_variable_test/1]).

size_variable_test(N) ->
    << Initial_char:N/bitstring, Rest_chars/bitstring >> = <<"ABC">>,
    Initial_char == << "A" >>,
    Rest_chars == << "BC" >>,
    {Initial_char, Rest_chars}.
```

**Comment by eternal-turtles** [comment]
I see. Thank you for the explanation and taking the time to look into this @rvirding

**Comment by rvirding** [comment]
@eternal-turtles I have looked some more into this and I was wrong there in that this is actually fully doable in LFE and wouldn't break anything either. The variable in a `(size name)` is never bound in the match and so its value is never exported. This means that even in LFE it is perfectly logical to import the value, but it must always be bound  before the pattern match.

I am working on this in the `develop-structs` branch, together with Elixir structs, and it will be merged into the `develop` branch soon.

**Comment by eternal-turtles** [comment]
That is great news. Looking forward to the next update to `develop`.

**Comment by GoNZooo** [comment]
@rvirding Did this end up making it into a release? I'm running 2.1.1 and it seems to still exhibit the same behavior. I see that you marked it as closed on Jan 18th, which is half a month after the last release.
