### ISSUE TITLE
Issues with LFE and Erlang 26.0 (user:start)

### ISSUE THREAD

**Issue by oubiwann** [lfe/lfe#474]
So far, this has manifested in the following:
* running the LFE REPL in Erlang 26.0
* running LFE as the shell in scripts 

Both use `user:start`. This is a known issue that @rvirding is looking into, we just hadn't created a ticket for it yet.

**Comment by rvirding** [comment]
These are two different but related issues. The `user` module has now been removed and the `io:get_line` function has been modified so that its history information is now no longer kept. Fortunately the call to `user_drv:start/1` we use still exists, explicitly for support for other systems, LFE, and Elixir, which use it.

I have now fixed or own `lfe_io:get_line` which saves the history information.

I am looking at how to replace the call to `user:start`.

**Comment by rvirding** [comment]
The question I haven't yet decided is whether to have this new get_line for general use or have it local to the LFE repl. I need to work out how much this will affect other things. But it will be used in the repl anyway.

**Comment by rvirding** [comment]
I have now create a new branch `develop-io` where I am working on this. First commit fixes the problem in `lfe_init.erl` with `user:start` and `user_drv:start` which should work for both OTP 26 and older versions. Could some one please test this branch with and older version of Erlang?

**Comment by rvirding** [comment]
The new `develop-io` branch is now complete and seems to work as expected. I will merge it.

**Comment by rvirding** [comment]
The `develop-io` branch has now been merged into `develop` and I will close this issue.
