### ISSUE TITLE
Quickstart problem

### ISSUE THREAD

**Issue by agadelshin** [lfe/lfe#70]
Hi, I try to run LFE REPL according to this manual http://lfe.github.io/quick-start/3.html, but I receive this message all the time

```
In order to run the LFE REPL from this script, it has to
be executed in its uncompressed form. For your convenience,
the script has just been uncompressed. Please re-execute
the same command to start the REPL.
```

Can you help me? Erlang 17.0

**Comment by rcarmo** [comment]
FYI, I just got this exact same problem with lfetool 1.3.2 _and_ 1.4.0 on Ubuntu 14.04.1. Not a good first impression for someone following the quickstart.

My fix was to remove lfetool altogether, reinstall and do a sudo lfetool upgrade, which shouldn't really be any different from a fresh install (which is what I had). 

I suggest you investigate this on a fresh system (VM, VPS, container, etc.)..

**Comment by rcarmo** [comment]
I can help test this on Mac OS X (Yosemite, with erlang via brew) and Ubuntu ARM (14.04.1, too) if you're interested.

**Comment by oubiwann** [comment]
Very cool! I don't use erlang via brew (I use kerl), so that will be
helpful -- ARM help is even better!

I'll give a shout when it's ready ...

Thanks so much!

d

**Comment by rcarmo** [comment]
No problem. `lfetool` 1.4 works fine on Ubuntu 14.04.1 on an ARM CPU:

```
Starting an LFE REPL ...
Erlang R16B03 (erts-5.10.4) [source] [smp:4:4] [async-threads:10] [kernel-poll:false]

LFE Shell V5.10.4 (abort with ^G)
> (os:type)
#(unix linux)
> (os:version)
#(3 8 13)
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
a
make: *** [repl-no-deps] Interrupt

odroid@odroid-server:~/Development/test-lib$ uname -a
Linux odroid-server 3.8.13.16 #1 SMP PREEMPT Tue Feb 11 10:47:21 BRST 2014 armv7l armv7l armv7l GNU/Linux
odroid@odroid-server:~/Development/test-lib$ 
```

**Comment by oubiwann** [comment]
On Mon, Jan 5, 2015 at 4:00 PM, Rui Carmo notifications@github.com wrote:

> I can help test this on Mac OS X (Yosemite, with erlang via brew) and
> Ubuntu ARM (14.04.1, too) if you're interested.
> 
> Thanks for your tests of the new (1.4) release the other day!

As previously mentioned, there's a new feature that's in the lfetool dev-v1
branch (per the request of Robert) that allows one to override the default
version pinning of rebar.

I've just spent my down-time during the past couple of days working my way
through this test plan:
- https://github.com/lfe/lfetool/issues/135#issuecomment-68797570

At the end of that fairly long ticket comment, you'll see the steps I took
to test this on Debian Jesse, Ubuntu 14.10, and CentOS 7.

For the most part, everything's working really well. However, I am getting
intermittent failures in project creation due  to rebar get-deps sometimes
not running. Oddly, retries on project creation have worked every time, so
far. There's a bug filed for this issue here:
- https://github.com/lfe/lfetool/issues/149

I wonder, now, if some of the complaints we've had are not actually related
to this issue. Hopefully we can crack that nut soon ...

If you are interested, it would be lovely if you could try this out on your
ARM setup -- but no worries if you have too little time right now. I'd say
that Robert's request is definitely a higher-priority.

Thanks again for your help, enthusiasm, and support!

d

**Comment by rcarmo** [comment]
@rvirding: On my ARM box (Running Ubuntu 14.04.1), `/usr/lib/erlang/lib/compiler-4.9.4/src` exists and has a number of source files (`beam`, etc.). 

They seem identical to an x86_64 install (only did a few spot checks). I might replace this with a `kerl` install soon, though, since I'm not too keen on Java being installed as a dependency in Ubuntu... _sigh_

For the sake of completeness, on a fresh install on my Mac, `erlang-17.4` on `brew` also has a `/usr/local/lib/erlang/lib/compiler-5.0.3/src` folder with `.erl`files.

Since I have a Raspberry Pi (running Raspbian, aka Debian 7.x) handy, I also checked that: the `R15B01` release they have on the repos _doesn't_ have a `src` dir. `/usr/lib/erlang/lib/compiler-4.8.1/` only has an `ebin` subdirectory.
